name: "Publish (Docs Only)"
description: "Build and push client documentation to Amazon EC2"

inputs:
  python-version:
    description: "Python version"
    required: true
  ssh-host:
    required: true
  ssh-user:
    required: true
  ssh-key:
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure SSH
      shell: bash
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" | sed 's/\\n/\n/g' > ~/.ssh/prod.key
        chmod 600 ~/.ssh/prod.key
        cat >~/.ssh/config <<END
        Host prod
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/prod.key
          StrictHostKeyChecking no
        END
      env:
        SSH_HOST: ${{ inputs.ssh-host }}
        SSH_USER: ${{ inputs.ssh-user }}
        SSH_KEY: ${{ inputs.ssh-key }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        cd wiki
        pip install -r requirements.txt

    - name: Build site
      shell: bash
      run: |
        cd wiki
        mkdocs build

    - name: Push files over ssh
      shell: bash
      run: |
        rsync -avz --delete wiki/site/ prod:/wiki/${{ github.event.repository.name }}/
