name: "Check code"
description: "Installeer dependencies en run linting en tests"

inputs:
  python-version:
    description: "Python versie"
    required: true
  from_ref:
    description: "Git ref (tag/branch/commit) vanaf waar commitizen de commits controleert"
    required: false
    default: "main"

runs:
  using: "composite"
  steps:
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install poetry
      run: pip install poetry
      shell: bash

    - name: Install dependencies
      run: poetry install --no-interaction --no-ansi
      shell: bash

    # Commit message convention
    - name: commitizen
      run: poetry run cz check --rev-range ${{ inputs.from_ref }}..HEAD
      shell: bash

    # Linting
    - name: Ruff
      run: poetry run ruff check .
      shell: bash

    # Code formatting
    - name: Black
      run: poetry run black --check .
      shell: bash

    # Type checking
    - name: Mypy
      run: poetry run mypy .
      shell: bash

    # Testing
    - name: Pytest
      run: poetry run pytest
      shell: bash