name: "Check code"
description: "Installeer dependencies en run linting en tests"

runs:
  using: "composite"
  steps:
    - name: Read Python version from pyproject.toml
      id: py
      run: |
        VERSION=$(grep "^python" pyproject.toml | sed -E 's/.*"([0-9]+\.[0-9]+)".*/\1/')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ steps.py.outputs.version }}

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
      shell: bash

    - name: Ruff (lint)
      run: poetry run ruff check .
      shell: bash

    - name: Black (format check)
      run: poetry run black --check .
      shell: bash

    - name: Mypy (type check)
      run: poetry run mypy .
      shell: bash

    - name: Run pytest
      run: poetry run pytest
      shell: bash