name: Setup Python with uv
description: Sets up Python, installs uv, and installs project dependencies

inputs:
  python-version:
    description: "Python version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install uv

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Install Project
      shell: bash
      run: uv sync --all-groups --all-extras --locked
