name: "Semantic Release"
description: "Automatically bump version using commit messages, update pyproject.toml, commit, and tag"

inputs:
  github_token:
    description: "GitHub token for pushing commits/tags"
    required: true

  git_user_name:
    description: "Git user.name to use for commits"
    required: false
    default: "github-actions[bot]"

  git_user_email:
    description: "Git user.email to use for commits"
    required: false
    default: "github-actions[bot]@users.noreply.github.com"

outputs:
  released:
    description: "Whether a new release was created (e.g., true or false)"
    value: ${{ steps.semantic.outputs.released }}
  version:
    description: "The latest version (e.g., 1.2.3)"
    value: ${{ steps.semantic.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Set up git user
      shell: bash
      run: |
        git config user.name "${{ inputs.git_user_name }}"
        git config user.email "${{ inputs.git_user_email }}"

    - name: Install Python Semantic Release
      shell: bash
      run: pip install python-semantic-release

    - name: Run semantic-release
      id: semantic
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        CURR=$(poetry version -s)

        semantic-release version || true
        
        NEXT=$(poetry version -s)
        
        echo "version=$NEXT" >> $GITHUB_OUTPUT

        if [ "$CURR" != "$NEXT" ]; then
          echo "released=true" >> $GITHUB_OUTPUT
        else
          echo "released=false" >> $GITHUB_OUTPUT
        fi