name: "Lint and test"

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.12"
    secrets:
      CI_PAT:
        required: false

permissions:
  contents: write

jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.CI_PAT || github.token }}

      - name: Setup Python & Poetry
        uses: cahido/actions/setup_python_poetry@main
        with:
          python-version: ${{ inputs.python-version }}

      - name: Check code formatting
        run: poetry run devtools lint check

  test:
    name: Python Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.CI_PAT || github.token }}

      - name: Setup Python & Poetry
        uses: cahido/actions/setup_python_poetry@main
        with:
          python-version: ${{ inputs.python-version }}


      - name: Run tests
        run: poetry run pytest
