name: "Lint and test"

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.12"
    secrets:
      CI_PAT:
        required: false

permissions:
  contents: write

jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.CI_PAT || github.token }}

      - name: Setup Python & Uv
        uses: cahido/actions/setup_python_uv@main
        with:
          python-version: ${{ inputs.python-version }}

      - name: Check code formatting
        run: uv run devtools lint check

      - name: Cache mypy cache
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: mypy-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('**/uv.lock', '**/pyproject.toml') }}
          restore-keys: |
            mypy-${{ runner.os }}-${{ inputs.python-version }}-

      - name: Check typing
        run: uv run devtools typecheck

  test:
    name: Python Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.CI_PAT || github.token }}

      - name: Setup Python & UV
        uses: cahido/actions/setup_python_uv@main
        with:
          python-version: ${{ inputs.python-version }}

      - name: Run tests
        run: uv run pytest
